seed_everything: 22341
trainer:
  max_epochs: 1000
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: 'logs/'
      name: 'test1/lr_test'
      default_hp_metric: False
  callbacks:
    - class_path: ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
    - class_path: EarlyStopping
      init_args:
        monitor: val_loss
        mode: min
        patience: 3
data:
  data_dir: '/content/data'
  batch_size: 64
  num_workers: 1
model:
  input_shape: [1, 28, 28]
  num_classes: 10
  patch_size: 4
  num_repeat: 3
  num_head: 4
  learning_rate: 1e-05 
  dropout: 0.1